import { test, expect } from '@playwright/test';
import { loginAsStudent } from '../../../../helpers/auth.js';

// Update these URLs if the mentor provides different surveys.
const AVAILABLE_SURVEY_URL = '/survey/alains-survey/';
const COMPLETED_SURVEY_URL = '/survey/wise-test-2/';

async function navigateToSurvey(page, surveyUrl) {
  await loginAsStudent(page);

  await page.getByRole('link', { name: 'All Surveys' }).click();

  await expect(page.locator('body')).toContainText(/survey/i);

  await page.goto(surveyUrl);

  await expect(page.locator('body')).toContainText(
    /survey|question|frontend|backend|full stack|development|skills|test/i
  );
}

async function fillSurvey(page) {
  // Radio buttons
  for (const radio of await page.locator('input[type="radio"]').all()) {
    if (await radio.isVisible().catch(() => false)) {
      await radio.check({ force: true }).catch(() => {});
    }
  }

  // Checkboxes
  for (const checkbox of await page.locator('input[type="checkbox"]').all()) {
    if (await checkbox.isVisible().catch(() => false)) {
      await checkbox.check({ force: true }).catch(() => {});
    }
  }

  // Standard inputs
  const inputs = page.locator(
    'input[type="text"], input[type="email"], input[type="number"], input[type="time"]'
  );

  const totalInputs = await inputs.count();

  for (let i = 0; i < totalInputs; i++) {
    const input = inputs.nth(i);

    if (!(await input.isVisible().catch(() => false))) continue;

    const type = await input.getAttribute('type');

    switch (type) {
      case 'email':
        await input.fill('playwright.feedback@example.com');
        break;

      case 'number':
        await input.fill('10');
        break;

      case 'time':
        await input.fill('09:30');
        break;

      default:
        await input.fill('Automated feedback generated by Playwright.');
    }
  }

  // Textareas
  const textareas = page.locator('textarea');
  const totalTextareas = await textareas.count();

  for (let i = 0; i < totalTextareas; i++) {
    const textarea = textareas.nth(i);

    if (await textarea.isVisible().catch(() => false)) {
      await textarea.fill(
        'This response was generated automatically during Playwright testing.'
      );
    }
  }

  // Select elements
  const selects = page.locator('select');
  const totalSelects = await selects.count();

  for (let i = 0; i < totalSelects; i++) {
    const select = selects.nth(i);

    if (!(await select.isVisible().catch(() => false))) continue;

    const options = select.locator('option');
    const count = await options.count();

    if (count > 1) {
      const value = await options.nth(1).getAttribute('value');

      if (value) {
        await select.selectOption(value);
      }
    }
  }

  // Sliders
  const sliders = page.getByRole('slider');
  const sliderCount = await sliders.count();

  for (let i = 0; i < sliderCount; i++) {
    const slider = sliders.nth(i);

    if (await slider.isVisible().catch(() => false)) {
      await slider.fill('5').catch(async () => {
        await slider.fill('50').catch(() => {});
      });
    }
  }
}

async function clickSubmit(page) {
  const submitButton = page
    .getByRole('button', { name: /submit/i })
    .or(page.locator('button[type="submit"]'))
    .or(page.locator('input[type="submit"]'));

  await expect(submitButton.first()).toBeVisible();

  await submitButton.first().scrollIntoViewIfNeeded();

  await submitButton.first().click();
}

test.describe.serial('Student Provide Feedback', () => {

  test('Student submits feedback successfully', async ({ page }) => {

    await navigateToSurvey(page, AVAILABLE_SURVEY_URL);

    await fillSurvey(page);

    await clickSubmit(page);

    await expect(page.locator('body')).toContainText(
      /Merci, vos réponses ont bien été enregistrées|Thank you/i
    );
  });

  test('Required questions prevent empty submission', async ({ page }) => {

    await navigateToSurvey(page, AVAILABLE_SURVEY_URL);

    await clickSubmit(page);

    await expect(page.locator('body')).toContainText(
      /Please fill out this field|Veuillez remplir ce champ|required|obligatoire/i
    );
  });

  test('Student cannot submit the same survey twice', async ({ page }) => {

    await navigateToSurvey(page, COMPLETED_SURVEY_URL);

    await expect(page.locator('body')).toContainText(
      /You have already responded to this survey|already responded|déjà répondu/i
    );
  });

});